# View goreleaser docs for configuration settings
# https://goreleaser.com

---
builds:
  - binary: pgcm
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: >
      -X github.com/gocardless/pgsql-cluster-manager/pkg/cmd.Version={{.Version}}
      -X github.com/gocardless/pgsql-cluster-manager/pkg/cmd.Commit={{.Commit}}
      -X github.com/gocardless/pgsql-cluster-manager/pkg/cmd.Date={{.Date}}
      -a
      -installsuffix cgo
    env:
      - CGO_ENABLED=0

dockers:
  - image: gocardless/pgsql-cluster-manager
    latest: true
    dockerfile: Dockerfile.release

brew:
  github:
    owner: gocardless
    name: homebrew-taps
  commit_author:
    name: GoCardless Engineering (goreleaser)
    email: engineering@gocardless.com
  folder: Formula
  homepage: https://github.com/gocardless/pgsql-cluster-manager
  description: Orchestrator for Postgres clustering with corosync/pacemaker/etcd

nfpm:
  vendor: GoCardless
  homepage: https://github.com/gocardless/pgsql-cluster-manager
  maintainer: GoCardless Engineering <engineering@gocardless.com>
  description: Orchestrator for Postgres clustering with corosync/pacemaker/etcd
  formats:
    - deb
