# View goreleaser docs for configuration settings
# https://goreleaser.com

---
builds:
  - binary: pgsql-cluster-manager
    ldflags: -X github.com/gocardless/pgsql-cluster-manager/command.Version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64

dockers:
  - image: gocardless/pgsql-cluster-manager
    latest: true
    dockerfile: Dockerfile.release

brew:
  github:
    owner: gocardless
    name: homebrew-taps
  commit_author:
    name: GoCardless Engineering (goreleaser)
    email: engineering@gocardless.com
  folder: Formula
  homepage: https://github.com/gocardless/pgsql-cluster-manager
  description: Orchestrator for Postgres clustering with corosync/pacemaker/etcd

fpm:
  vendor: GoCardless
  homepage: https://github.com/gocardless/pgsql-cluster-manager
  maintainer: GoCardless Engineering <engineering@gocardless.com>
  description: Orchestrator for Postgres clustering with corosync/pacemaker/etcd
  formats:
    - deb
