# For all options see https://github.com/bbatsov/rubocop/tree/master/config

AllCops:
  DisplayCopNames: true
  Exclude:
    - vendor/**/*

Lint/UnneededDisable:
  Severity: error

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 90

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

# Allow non-ASCII characters (e.g. £) in comments
Style/AsciiComments:
  Enabled: false

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method

Style/Documentation:
  Enabled: false

# Use trailing rather than leading dots on multi-line call chains
Layout/DotPosition:
  EnforcedStyle: trailing

# Magic encoding comment only relevant on ruby-1.9 or non-utf8
Style/Encoding:
  Enabled: never

Style/FormatString:
  EnforcedStyle: sprintf

Style/FrozenStringLiteralComment:
  Enabled: always

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# As of 0.43.0 this cop complains in situations where a guard clause would be
# unhelpful or erroneous.
# The auto-correct is also buggy.
Style/GuardClause:
  Enabled: false

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Style/Lambda:
  EnforcedStyle: literal

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'

Style/NumericLiterals:
  MinDigits: 11

Style/SignalException:
  EnforcedStyle: 'only_raise'

# Wants you to use the same argument names for every reduce. This seems kinda
# naff compared to naming them semantically
Style/SingleLineBlockParams:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/VariableNumber:
  Enabled: false

# TODO: Re-enable me when upgrading from Rubocop 0.49.0 - there are bugs in this version,
# which cause it to be broken in various ways. They're fixed in master.
Style/YodaCondition:
  Enabled: false
