---
version: 2

references:
  docker_login: &docker_login
    run:
      name: Login to GoCardless DockerHub
      command: docker login -u $DOCKER_USER -p $DOCKER_PASS

  docker_build_image: &docker_build_image
    working_directory: /go/src/github.com/gocardless/pgsql-cluster-manager
    docker:
      - image: gocardless/pgsql-cluster-manager-circleci:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
        environment:
          BUNDLE_PATH: vendor/bundle

jobs:
  unit:
    <<: *docker_build_image
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: make test

  build:
    <<: *docker_build_image
    steps:
      - checkout
      - run:
          name: Build test binaries
          command: make bin/pgcm.linux_amd64 bin/pgcm-acceptance
      - persist_to_workspace:
          root: /go/src/github.com/gocardless/pgsql-cluster-manager
          paths: ['bin/pgcm.linux_amd64', 'bin/pgcm-acceptance']

  integration:
    machine: true
    environment:
      PGSQL_WORKSPACE: /home/circleci/project/workspace
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - *docker_login
      - run:
          name: Pull gocardless/pgsql-cluster-manager-base image
          command: docker pull gocardless/pgsql-cluster-manager-base
      - run:
          name: Build postgres member image
          command: make docker-postgres-member
      - run:
          name: Run integration tests
          command: workspace/bin/pgcm-acceptance

workflows:
  version: 2
  build-integration:
    jobs:
      - unit
      - build
      - integration:
          requires: [build]
