version: 2

references:
  docker_login: &docker_login
    run:
      name: Login to GoCardless DockerHub
      command: docker login -u $DOCKER_USER -p $DOCKER_PASS

  docker_build_image: &docker_build_image
    working_directory: /home/circleci/go/src/github.com/gocardless/pgsql-cluster-manager
    docker:
      - image: gocardless/pgsql-cluster-manager-circleci:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
        environment:
          BUNDLE_PATH: vendor/bundle

jobs:
  unit:
    <<: *docker_build_image
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: make test

  build:
    <<: *docker_build_image
    steps:
      - checkout
      - run:
          name: Build linux test binary
          command: make build-linux
      - run:
          name: Build integration test binary
          command: make build-integration
      - persist_to_workspace:
          root: /home/circleci/go/src/github.com/gocardless/pgsql-cluster-manager
          paths: ['pgsql-cluster-manager.linux_amd64', 'integration.test']

  integration:
    machine: true
    environment:
      PGSQL_WORKSPACE: /home/circleci/project/workspace
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - *docker_login
      - run:
          name: Pull gocardless/pgsql-cluster-manager-base image
          command: docker pull gocardless/pgsql-cluster-manager-base
      - run:
          name: Build postgres member image
          command: make build-postgres-member-dockerfile
      - run:
          name: Run integration tests
          command: workspace/integration.test -test.v

workflows:
  version: 2
  build-integration:
    jobs:
      - unit
      - build
      - integration:
          requires: [build]
